fix missing ´name´attribute
Fix this error :
ERROR: Cookbook loaded at path(s) [/tmp/vagrant-chef-4/chef-solo-1/cookbooks/drush] has invalid metadata: The `name' attribute is required in cookbook metadata